title: Project
pages: false
files: true
  sortable: true
  fields:
    alt:
      label: Alt Text
      type: text
    caption:
      label: Caption
      type: text
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  coverImage:
    label: Cover Image
    type: image
  type:
    label: Project Type
    type: tags
