title: Site
tabs:
  dashboard:
    label: Dashboard
    icon: dashboard
    columns:
      - width: 2/3
        sections:
          projects: sections/projects
      - width: 1/3
        sections:
          pages:
            type: pages
            create: default
          notes: sections/notes
  settings:
    label: Settings
    icon: cog
    fields:
      title:
        label: Title
        type:  text
      description:
        label: Description
        type:  text
      copyright:
        label: Copyright
        type:  textarea
        size: small
